# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 AS base
WORKDIR /usr/app

# copy the source code



# run the app
USER bun
EXPOSE 8000/tcp
ENTRYPOINT [ "bun", "--bun", "run", "b:" ]